name: Build and Release

on:
  push:
    branches: [main, develop]
    tags: ["v*", "*.*.*", "*.*.*-*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r src/python/cut-quiet-parts/requirements.txt
          pip install pyinstaller

      - name: Build Python executables
        run: npm run build:python
        timeout-minutes: 40

      - name: Build application
        run: npm run build

      - name: Build distributables (Windows x64)
        run: npm run dist:quick -- --win
        if: matrix.os == 'windows-latest'
        timeout-minutes: 30
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build distributables (macOS)
        run: npm run dist:quick -- --mac
        if: matrix.os == 'macos-latest'
        timeout-minutes: 30
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build distributables (Linux)
        run: npm run dist:quick -- --linux
        if: matrix.os == 'ubuntu-latest'
        timeout-minutes: 30
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            release/**/*
            !release/win-unpacked/**/*
            !release/mac/**/*
            !release/linux-unpacked/**/*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-latest-build/**/*.exe
            artifacts/windows-latest-build/**/*.exe.blockmap
            artifacts/windows-latest-build/**/latest.yml
            artifacts/macos-latest-build/**/*.dmg
            artifacts/macos-latest-build/**/*.dmg.blockmap
            artifacts/macos-latest-build/**/latest-mac.yml
            artifacts/ubuntu-latest-build/**/*.AppImage
            artifacts/ubuntu-latest-build/**/latest-linux.yml
          draft: false
          prerelease: contains(github.ref, 'beta') || contains(github.ref, 'alpha')
          generate_release_notes: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
